# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_to_worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_to_worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16master_to_worker.proto\"\xa5\x01\n\x07JobInfo\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x0f\n\x07node_id\x18\x02 \x03(\r\x12\x0e\n\x06job_id\x18\x03 \x03(\x05\x12\x10\n\x08job_name\x18\x04 \x03(\t\x12\x12\n\nbatch_size\x18\x05 \x03(\r\x12\x12\n\niterations\x18\x06 \x03(\r\x12\x0c\n\x04gpus\x18\x07 \x01(\t\x12\x13\n\x0bjob_counter\x18\x08 \x03(\r\x12\x0f\n\x07num_gpu\x18\t \x01(\r\",\n\x0e\x45xecuteRequest\x12\x1a\n\x08job_info\x18\x01 \x01(\x0b\x32\x08.JobInfo\"\"\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\")\n\x0bKillRequest\x12\x1a\n\x08job_info\x18\x01 \x01(\x0b\x32\x08.JobInfo\"\x1f\n\x0cKillResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12\x45xitCommandRequest\"&\n\x13\x45xitCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0eGetUtilRequest\x12\x0c\n\x04secs\x18\x01 \x01(\r\"F\n\x0fGetUtilResponse\x12\x10\n\x08gpu_util\x18\x01 \x01(\x01\x12\x10\n\x08\x63pu_util\x18\x02 \x01(\x01\x12\x0f\n\x07io_read\x18\x03 \x01(\x01\x32\xd3\x01\n\x0eMasterToWorker\x12.\n\x07\x45xecute\x12\x0f.ExecuteRequest\x1a\x10.ExecuteResponse\"\x00\x12%\n\x04Kill\x12\x0c.KillRequest\x1a\r.KillResponse\"\x00\x12:\n\x0b\x45xitCommand\x12\x13.ExitCommandRequest\x1a\x14.ExitCommandResponse\"\x00\x12.\n\x07GetUtil\x12\x0f.GetUtilRequest\x1a\x10.GetUtilResponse\"\x00\x62\x06proto3'
)




_JOBINFO = _descriptor.Descriptor(
  name='JobInfo',
  full_name='JobInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='JobInfo.num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='JobInfo.node_id', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='JobInfo.job_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='JobInfo.job_name', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='JobInfo.batch_size', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iterations', full_name='JobInfo.iterations', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpus', full_name='JobInfo.gpus', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_counter', full_name='JobInfo.job_counter', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_gpu', full_name='JobInfo.num_gpu', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=192,
)


_EXECUTEREQUEST = _descriptor.Descriptor(
  name='ExecuteRequest',
  full_name='ExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_info', full_name='ExecuteRequest.job_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=238,
)


_EXECUTERESPONSE = _descriptor.Descriptor(
  name='ExecuteResponse',
  full_name='ExecuteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ExecuteResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=274,
)


_KILLREQUEST = _descriptor.Descriptor(
  name='KillRequest',
  full_name='KillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_info', full_name='KillRequest.job_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=317,
)


_KILLRESPONSE = _descriptor.Descriptor(
  name='KillResponse',
  full_name='KillResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='KillResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=350,
)


_EXITCOMMANDREQUEST = _descriptor.Descriptor(
  name='ExitCommandRequest',
  full_name='ExitCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=372,
)


_EXITCOMMANDRESPONSE = _descriptor.Descriptor(
  name='ExitCommandResponse',
  full_name='ExitCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ExitCommandResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=412,
)


_GETUTILREQUEST = _descriptor.Descriptor(
  name='GetUtilRequest',
  full_name='GetUtilRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='secs', full_name='GetUtilRequest.secs', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=444,
)


_GETUTILRESPONSE = _descriptor.Descriptor(
  name='GetUtilResponse',
  full_name='GetUtilResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpu_util', full_name='GetUtilResponse.gpu_util', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpu_util', full_name='GetUtilResponse.cpu_util', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='io_read', full_name='GetUtilResponse.io_read', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=516,
)

_EXECUTEREQUEST.fields_by_name['job_info'].message_type = _JOBINFO
_KILLREQUEST.fields_by_name['job_info'].message_type = _JOBINFO
DESCRIPTOR.message_types_by_name['JobInfo'] = _JOBINFO
DESCRIPTOR.message_types_by_name['ExecuteRequest'] = _EXECUTEREQUEST
DESCRIPTOR.message_types_by_name['ExecuteResponse'] = _EXECUTERESPONSE
DESCRIPTOR.message_types_by_name['KillRequest'] = _KILLREQUEST
DESCRIPTOR.message_types_by_name['KillResponse'] = _KILLRESPONSE
DESCRIPTOR.message_types_by_name['ExitCommandRequest'] = _EXITCOMMANDREQUEST
DESCRIPTOR.message_types_by_name['ExitCommandResponse'] = _EXITCOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['GetUtilRequest'] = _GETUTILREQUEST
DESCRIPTOR.message_types_by_name['GetUtilResponse'] = _GETUTILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobInfo = _reflection.GeneratedProtocolMessageType('JobInfo', (_message.Message,), {
  'DESCRIPTOR' : _JOBINFO,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:JobInfo)
  })
_sym_db.RegisterMessage(JobInfo)

ExecuteRequest = _reflection.GeneratedProtocolMessageType('ExecuteRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:ExecuteRequest)
  })
_sym_db.RegisterMessage(ExecuteRequest)

ExecuteResponse = _reflection.GeneratedProtocolMessageType('ExecuteResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTERESPONSE,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:ExecuteResponse)
  })
_sym_db.RegisterMessage(ExecuteResponse)

KillRequest = _reflection.GeneratedProtocolMessageType('KillRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:KillRequest)
  })
_sym_db.RegisterMessage(KillRequest)

KillResponse = _reflection.GeneratedProtocolMessageType('KillResponse', (_message.Message,), {
  'DESCRIPTOR' : _KILLRESPONSE,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:KillResponse)
  })
_sym_db.RegisterMessage(KillResponse)

ExitCommandRequest = _reflection.GeneratedProtocolMessageType('ExitCommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXITCOMMANDREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:ExitCommandRequest)
  })
_sym_db.RegisterMessage(ExitCommandRequest)

ExitCommandResponse = _reflection.GeneratedProtocolMessageType('ExitCommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXITCOMMANDRESPONSE,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:ExitCommandResponse)
  })
_sym_db.RegisterMessage(ExitCommandResponse)

GetUtilRequest = _reflection.GeneratedProtocolMessageType('GetUtilRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUTILREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:GetUtilRequest)
  })
_sym_db.RegisterMessage(GetUtilRequest)

GetUtilResponse = _reflection.GeneratedProtocolMessageType('GetUtilResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUTILRESPONSE,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:GetUtilResponse)
  })
_sym_db.RegisterMessage(GetUtilResponse)



_MASTERTOWORKER = _descriptor.ServiceDescriptor(
  name='MasterToWorker',
  full_name='MasterToWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=519,
  serialized_end=730,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='MasterToWorker.Execute',
    index=0,
    containing_service=None,
    input_type=_EXECUTEREQUEST,
    output_type=_EXECUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Kill',
    full_name='MasterToWorker.Kill',
    index=1,
    containing_service=None,
    input_type=_KILLREQUEST,
    output_type=_KILLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExitCommand',
    full_name='MasterToWorker.ExitCommand',
    index=2,
    containing_service=None,
    input_type=_EXITCOMMANDREQUEST,
    output_type=_EXITCOMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUtil',
    full_name='MasterToWorker.GetUtil',
    index=3,
    containing_service=None,
    input_type=_GETUTILREQUEST,
    output_type=_GETUTILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERTOWORKER)

DESCRIPTOR.services_by_name['MasterToWorker'] = _MASTERTOWORKER

# @@protoc_insertion_point(module_scope)
