# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_to_worker_pb2 as master__to__worker__pb2


class MasterToWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/MasterToWorker/Execute',
                request_serializer=master__to__worker__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=master__to__worker__pb2.ExecuteResponse.FromString,
                )
        self.Kill = channel.unary_unary(
                '/MasterToWorker/Kill',
                request_serializer=master__to__worker__pb2.KillRequest.SerializeToString,
                response_deserializer=master__to__worker__pb2.KillResponse.FromString,
                )
        self.ExitCommand = channel.unary_unary(
                '/MasterToWorker/ExitCommand',
                request_serializer=master__to__worker__pb2.ExitCommandRequest.SerializeToString,
                response_deserializer=master__to__worker__pb2.ExitCommandResponse.FromString,
                )
        self.GetUtil = channel.unary_unary(
                '/MasterToWorker/GetUtil',
                request_serializer=master__to__worker__pb2.GetUtilRequest.SerializeToString,
                response_deserializer=master__to__worker__pb2.GetUtilResponse.FromString,
                )


class MasterToWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUtil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterToWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=master__to__worker__pb2.ExecuteRequest.FromString,
                    response_serializer=master__to__worker__pb2.ExecuteResponse.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=master__to__worker__pb2.KillRequest.FromString,
                    response_serializer=master__to__worker__pb2.KillResponse.SerializeToString,
            ),
            'ExitCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitCommand,
                    request_deserializer=master__to__worker__pb2.ExitCommandRequest.FromString,
                    response_serializer=master__to__worker__pb2.ExitCommandResponse.SerializeToString,
            ),
            'GetUtil': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUtil,
                    request_deserializer=master__to__worker__pb2.GetUtilRequest.FromString,
                    response_serializer=master__to__worker__pb2.GetUtilResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterToWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterToWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterToWorker/Execute',
            master__to__worker__pb2.ExecuteRequest.SerializeToString,
            master__to__worker__pb2.ExecuteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterToWorker/Kill',
            master__to__worker__pb2.KillRequest.SerializeToString,
            master__to__worker__pb2.KillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExitCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterToWorker/ExitCommand',
            master__to__worker__pb2.ExitCommandRequest.SerializeToString,
            master__to__worker__pb2.ExitCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUtil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterToWorker/GetUtil',
            master__to__worker__pb2.GetUtilRequest.SerializeToString,
            master__to__worker__pb2.GetUtilResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
